#!/bin/sh

set -e
#  Copyright 2010 Neil Williams <codehelp@debian.org>
#
#  This package is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

. gettext.sh
TEXTDOMAIN="xapt"
export TEXTDOMAIN
TEXTDOMAINDIR="/usr/share/locale/"
export TEXTDOMAINDIR

cfg="/etc/pdebuild-cross/pdebuild-cross.rc"
if [ ! -f $cfg ]; then
	eval_gettext "\$cfg does not exist!"; echo
	exit 1
fi
. $cfg

if [ ! -d $BUILDPLACE ]; then
	mkdir -p $BUILDPLACE
fi

if [ ! -f $BASETGZ ]; then
	eval_gettext "Need to create a new pbuilder crossbuilding chroot first."; echo
	eval_gettext "Use pdebuild-cross-create to create one."; echo
	exit 2
fi

eval_gettext "Enter your sudo password if prompted"; echo
sudo pbuilder update --configfile $cfg
